# Generated by Django 2.2.5 on 2019-09-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
