# Generated by Django 2.2.5 on 2019-09-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20190917_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
