# Generated by Django 2.2.5 on 2019-12-24 19:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ColourFamilies',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Colour Families',
            },
        ),
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_families', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_val', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Colours',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('main_colour', models.BooleanField(default=True)),
                ('sub_categories', models.CharField(blank=True, max_length=128)),
                ('height', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('features', models.CharField(blank=True, max_length=100)),
                ('related', models.CharField(blank=True, max_length=100, null=True)),
                ('showcase_image', models.ImageField(upload_to='products/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('price', models.FloatField()),
                ('rating', models.FloatField(default=99)),
                ('ratings', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('inventory', models.IntegerField()),
                ('delivery_available', models.BooleanField()),
                ('delivery_price', models.FloatField(default=-1)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Categories')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Colours')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Categories')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='RelatedProductVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='products.Products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_item', to='products.Products')),
            ],
            options={
                'verbose_name_plural': 'Related Product Variations',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Rooms'),
        ),
        migrations.AddField(
            model_name='products',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Stores'),
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comments', models.CharField(blank=True, max_length=2048)),
                ('review_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Stores')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='ProductColourVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_colour_prod', to='products.Products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_col_prod', to='products.Products')),
            ],
            options={
                'verbose_name_plural': 'Related Colour Variations',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Categories')),
            ],
            options={
                'verbose_name_plural': 'Features',
            },
        ),
    ]
