# Generated by Django 2.2.5 on 2019-12-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191226_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedproducts',
            name='related_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='products.Products'),
        ),
        migrations.AlterField(
            model_name='linkedproducts',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.Products'),
        ),
        migrations.AlterField(
            model_name='linkedproducts',
            name='relation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='products.RelationType'),
        ),
    ]
