# Generated by Django 2.2.5 on 2019-12-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_linkedproducts_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Features')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
        ),
    ]
