# Generated by Django 2.2.5 on 2019-12-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productfeatures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedproducts',
            options={'verbose_name_plural': 'Linked Products'},
        ),
        migrations.AlterModelOptions(
            name='productfeatures',
            options={'verbose_name_plural': 'Product Features'},
        ),
        migrations.AlterModelOptions(
            name='relationtype',
            options={'verbose_name_plural': 'Relation Types'},
        ),
    ]
