# Generated by Django 2.2.5 on 2020-02-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191229_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='review_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='comments',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
