# Generated by Django 2.2.5 on 2019-09-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='storereviews',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='country_code',
            new_name='country',
        ),
    ]
