# Generated by Django 2.2.5 on 2019-09-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20190923_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='rating',
        ),
        migrations.AddField(
            model_name='stores',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
