# Generated by Django 2.2.5 on 2019-09-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20190923_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveries',
            options={'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='storereviews',
            options={'verbose_name_plural': 'Store Reviews'},
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={'verbose_name_plural': 'Stores'},
        ),
    ]
