# Generated by Django 2.2.5 on 2019-09-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20190927_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
