# Generated by Django 2.2.5 on 2019-09-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_stores_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
