# Generated by Django 2.2.5 on 2020-01-24 22:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_auto_20200123_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='assembly',
            new_name='assembly_price',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='delivery',
            new_name='delivery_price',
        ),
        migrations.AddField(
            model_name='sales',
            name='address_line_1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='address_line_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='city',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.DO_NOTHING, to='misc.Cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='country',
            field=models.ForeignKey(default='GBR', on_delete=django.db.models.deletion.DO_NOTHING, to='misc.Countries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='delivered_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='delivery_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='delivery_included',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='delivery_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='ordered_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='postcode',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='recipient',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='return_by',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='returned_allowed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='returned_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='tracking_ref',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
