# Generated by Django 2.2.5 on 2020-01-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20200125_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='exVat',
            new_name='ex_vat',
        ),
        migrations.AlterField(
            model_name='deliveraddresses',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='return_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='returned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
