# Generated by Django 2.2.5 on 2019-09-16 23:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_auto_20190917_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_val', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('height', models.FloatField(blank=True)),
                ('length', models.FloatField(blank=True)),
                ('width', models.FloatField(blank=True)),
                ('weight', models.FloatField(blank=True)),
                ('features', models.CharField(blank=True, max_length=100)),
                ('related', models.CharField(blank=True, max_length=100)),
                ('variations_with_alt_colours', models.CharField(blank=True, max_length=100)),
                ('variations_with_alt_sizes', models.CharField(blank=True, max_length=100)),
                ('showcase_image', models.ImageField(upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.BigAutoField>/')),
                ('image_1', models.ImageField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.BigAutoField>/')),
                ('image_2', models.ImageField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.BigAutoField>/')),
                ('image_3', models.ImageField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.BigAutoField>/')),
                ('image_4', models.ImageField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.BigAutoField>/')),
                ('image_5', models.ImageField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.BigAutoField>/')),
                ('image_6', models.ImageField(blank=True, upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.BigAutoField>/')),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('price', models.FloatField()),
                ('rating', models.FloatField(blank=True)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_purchase_date', models.DateTimeField(blank=True)),
                ('inventory', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Categories')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Colours')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Rooms')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Stores')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField()),
                ('comments', models.CharField(blank=True, max_length=2048)),
                ('review_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Stores')),
            ],
        ),
    ]
