# Generated by Django 2.2.5 on 2019-09-17 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productreviews',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='store_id',
            new_name='store',
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
