# Generated by Django 2.2.5 on 2019-09-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190917_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='delivery_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='delivery_price',
            field=models.FloatField(blank=True, default=0.0),
            preserve_default=False,
        ),
    ]
