# Generated by Django 2.2.5 on 2019-12-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('products', '0003_auto_20191224_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedProducts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'LinkedProducts',
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('relation', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'RelationTypes',
            },
        ),
        migrations.RemoveField(
            model_name='relatedproductvars',
            name='linked',
        ),
        migrations.RemoveField(
            model_name='relatedproductvars',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='height_units',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='length_units',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='weight_units',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='width_units',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ProductColourVars',
        ),
        migrations.DeleteModel(
            name='RelatedProductVars',
        ),
        migrations.AddField(
            model_name='linkedproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products'),
        ),
        migrations.AddField(
            model_name='linkedproducts',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.RelationType'),
        ),
        migrations.AddField(
            model_name='linkedproducts',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Stores'),
        ),
    ]
