# Generated by Django 2.2.5 on 2019-09-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190922_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourfamilies',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
