# Generated by Django 2.2.5 on 2019-09-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190922_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colours',
            name='family',
        ),
        migrations.AddField(
            model_name='colours',
            name='col_families',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
