# Generated by Django 2.2.5 on 2019-09-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190922_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colourfamilies',
            name='id',
        ),
        migrations.AlterField(
            model_name='colourfamilies',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
