# Generated by Django 2.2.5 on 2019-09-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190922_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='valid_features',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SubCateogires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Categories')),
            ],
        ),
    ]
