# Generated by Django 2.2.5 on 2019-09-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190922_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_categories',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
