# Generated by Django 2.2.5 on 2020-02-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200202_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='related',
        ),
    ]
