# Generated by Django 2.2.5 on 2019-09-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190922_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='variations_with_alt_colours',
        ),
        migrations.RemoveField(
            model_name='products',
            name='variations_with_alt_sizes',
        ),
        migrations.AddField(
            model_name='products',
            name='main_color',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RelatedProductVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='products.Products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_item', to='products.Products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColourVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_colour_prod', to='products.Products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_col_prod', to='products.Products')),
            ],
        ),
    ]
