# Generated by Django 2.2.5 on 2019-09-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20190929_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='showcase_image',
            field=models.ImageField(upload_to='products/{product_id}/'),
        ),
    ]
