# Generated by Django 2.2.5 on 2019-10-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20190930_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colours',
            name='hex_val',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
