# Generated by Django 2.2.5 on 2019-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20191003_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.FloatField(default=99),
        ),
    ]
