# Generated by Django 2.2.5 on 2019-10-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20191027_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='related',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
