# Generated by Django 2.2.5 on 2019-11-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20191027_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='features',
            name='feature_id',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
